# ABOUTME: Pre-commit hook configuration for Go project quality checks
# ABOUTME: Runs formatting, linting, and tests before each commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        name: go fmt
        description: Run go fmt on Go source files
      - id: go-vet
        name: go vet
        description: Run go vet on Go source files
      - id: go-imports
        name: goimports
        description: Run goimports on Go source files
      - id: go-unit-tests
        name: go test
        description: Run Go unit tests
        args: ['./pkg/...']
      - id: go-build
        name: go build
        description: Build Go binaries
      - id: go-mod-tidy
        name: go mod tidy
        description: Ensure go.mod and go.sum are up to date

# Note: golangci-lint is run in GitHub Actions CI instead of pre-commit
# to avoid compatibility issues and speed up local commits.
